[[envs]]
key = "PATH"
value = [
	"TESTDIR/TESTO/1919/",
	"D:\\win\\dev-tools\\mpv\\",
	"D:\\win\\program\\py\\main-project\\checkitems\\dist",
	"D:\\win\\dev-tools\\neovim\\app\\bin\\"
]

[[envs]]
key = "TEST_ENVS"
value = [
	"12345あいえうお",
	"6789かきくけこ",
]

